<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<StartupObject>Telenec.Mail.App.Program</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\Brand\TelenecLogo.png" />
		<None Remove="Assets\Brand\TelenecMailLogo.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
		<PackageReference Include="Velopack" Version="1.2.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\Brand\TelenecLogo.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>

		<Resource Include="Assets\Brand\TelenecMailLogo.png">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

</Project>