namespace Telenec.Mail.App.Models;

public sealed record MailMessageData(
    string Sender,
    string SenderAddress,
    string RecipientAddress,
    string Subject,
    string Preview,
    string DisplayTime,
    string DisplayDateTime,
    string SenderInitial,
    string Greeting,
    string Body,
    string Closing,
    string Signature,
    bool IsUnread = false,
    bool EmphasizeSender = false,
    string? HighlightTitle = null,
    string? HighlightText = null,
    string? HtmlBody = null,
    uint UniqueId = 0,
    IReadOnlyList<MailAttachmentData>? Attachments = null,
    bool HasSmimeSignature = false,
    string? MessageId = null,
    IReadOnlyList<string>? References = null,
    IReadOnlyList<string>? ToAddresses = null,
    IReadOnlyList<string>? CcAddresses = null,
    IReadOnlyList<string>? ReplyToAddresses = null);